name: Deploy Flask App to DigitalOcean

on:
  push:
    branches:
      - main  # Or use 'master' if that's your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: SSH to Server and Deploy
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${USERNAME}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/PCP
          git pull origin main  # Pull the latest changes from GitHub
          source venv/bin/activate
          pip install -r requirements.txt  # Reinstall dependencies if needed
          sudo systemctl restart nginx  # Restart Nginx to apply changes
          sudo systemctl restart gunicorn  # Restart Gunicorn (if using Gunicorn to serve the app)
        EOF
