name: Deploy Flask App to DigitalOcean

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Update to the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create SSH directory and set permissions
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh  # Ensure the directory has the correct permissions

      - name: Copy SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set the private key file to be read-only
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Key to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Ensure the known_hosts file has the correct permissions

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /path/to/your/app
            git pull origin main
            source /path/to/venv/bin/activate  # If using a virtualenv
            pip install -r requirements.txt
            sudo systemctl restart your-service-name  # If you're using systemd or any other service manager
          EOF
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
